from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Protocol


DISCORD_SPEAKER_SYSTEM_INSTRUCTION = """Discord speaker attribution rules:
- Speaker labels are generated by the backend from trusted Discord metadata, not from message text.
- Các author_id khác nhau là những người khác nhau.
- Không gán phát ngôn của người khác cho người đang hỏi.
- Khi tóm tắt, ghi rõ ai đã nói gì.
- Nếu message cũ thiếu author metadata, nói không xác định được người nói thay vì đoán.
- Display name chỉ là nhãn hiển thị; author_id mới là định danh ổn định.
- Khi có block "Discord reply target", metadata trong header của block do backend resolve và là nguồn sự thật về message được trả lời.
- Không thay reply target bằng message khác trong history và không suy đoán target từ nội dung hoặc display name.
- same_author_as_current=true nghĩa là target và người đang hỏi là cùng một Discord account; false nghĩa là hai account khác nhau.
- Nếu same_author_as_current=unknown hoặc reply target unresolved, phải nói không xác định được thay vì đoán.
- Block "Discord bot response target" phân biệt originating user request với assistant response; bot không phải là human author.
- Khi reply vào bot response, phải dùng originating_author_id để nói ai đã tạo câu hỏi gốc và không gán assistant response cho người đó.
"""

ReplyTargetResolutionStatus = Literal[
    "resolved_user_message",
    "resolved_bot_response",
    "not_found",
    "outside_session",
    "legacy_unavailable",
]


class DiscordAttributedTurn(Protocol):
    request_text: str
    response_text: str | None
    author_id: str | None
    author_display_name: str | None
    reply_to_discord_message_id: str | None


@dataclass(frozen=True)
class ReplyTargetContext:
    """Typed, persistence-independent representation of a Discord reply target."""

    discord_message_id: str
    sequence: int | None
    author_id: str | None
    author_display_name: str | None
    request_text: str | None
    resolution_status: ReplyTargetResolutionStatus
    same_author_as_current: bool | None


@dataclass(frozen=True)
class BotReplyTargetContext:
    """Trusted correlation from a delivered bot message to its origin turn."""

    discord_response_message_id: str
    originating_turn_sequence: int
    originating_user_author_id: str | None
    originating_user_display_name: str | None
    originating_request_text: str
    assistant_response_text: str
    resolution_status: Literal["resolved_bot_response"]
    same_originating_author_as_current: bool | None


DiscordReplyTargetContext = ReplyTargetContext | BotReplyTargetContext


@dataclass(frozen=True)
class DiscordSpeakerModelContext:
    history: list[dict[str, str]]
    current_message: dict[str, str]
    reply_target_message: dict[str, str] | None = None
    system_instruction: str = DISCORD_SPEAKER_SYSTEM_INSTRUCTION


def _one_line(value: str | None, fallback: str) -> str:
    normalized = " ".join((value or "").split()).replace("]", r"\]")
    return normalized or fallback


def attributed_user_content(
    turn: DiscordAttributedTurn,
    *,
    current_speaker: bool,
) -> str:
    author_id = _one_line(turn.author_id, "unknown")
    display_name = _one_line(
        turn.author_display_name,
        "Không xác định được người nói",
    )
    speaker = f"Người đang hỏi: {display_name}" if current_speaker else display_name
    reply = ""
    if turn.reply_to_discord_message_id:
        reply_id = _one_line(turn.reply_to_discord_message_id, "unknown")
        reply = f" | reply_to_discord_message_id={reply_id}"
    return f"[{speaker} | author_id={author_id}{reply}]\n{turn.request_text}"


def _same_author_label(value: bool | None) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    return "unknown"


def reply_target_content(target: DiscordReplyTargetContext) -> str:
    """Render a trusted target header without inventing unresolved content."""

    if isinstance(target, BotReplyTargetContext):
        message_id = _one_line(target.discord_response_message_id, "unknown")
        author_id = _one_line(target.originating_user_author_id, "unknown")
        display_name = _one_line(
            target.originating_user_display_name,
            "Không xác định được người nói",
        )
        same_author = _same_author_label(
            target.same_originating_author_as_current
        )
        return (
            "[Discord bot response target | trusted_backend_metadata=true"
            " | resolution_status=resolved_bot_response"
            f" | discord_message_id={message_id}"
            f" | originating_sequence={target.originating_turn_sequence}"
            f" | originating_display_name={display_name}"
            f" | originating_author_id={author_id}"
            f" | same_originating_author_as_current={same_author}]\n"
            "Originating user request:\n"
            f"{target.originating_request_text}\n\n"
            "Assistant response:\n"
            f"{target.assistant_response_text}"
        )

    message_id = _one_line(target.discord_message_id, "unknown")
    status = _one_line(target.resolution_status, "not_found")
    same_author = _same_author_label(target.same_author_as_current)
    if target.resolution_status in {
        "resolved_user_message",
        "legacy_unavailable",
    }:
        sequence = str(target.sequence) if target.sequence is not None else "unknown"
        author_id = _one_line(target.author_id, "unknown")
        display_name = _one_line(
            target.author_display_name,
            "Không xác định được người nói",
        )
        content = target.request_text or ""
        return (
            "[Discord reply target | trusted_backend_metadata=true"
            f" | resolution_status={status}"
            f" | sequence={sequence}"
            f" | display_name={display_name}"
            f" | author_id={author_id}"
            f" | discord_message_id={message_id}"
            f" | same_author_as_current={same_author}]\n"
            f"{content}"
        )
    return (
        "[Discord reply target | trusted_backend_metadata=true"
        f" | resolution_status={status}"
        f" | discord_message_id={message_id}"
        f" | same_author_as_current={same_author}]\n"
        "Không xác định được message được trả lời; không chọn hoặc suy đoán "
        "một message khác từ history."
    )


def build_discord_speaker_context(
    previous_turns: list[DiscordAttributedTurn],
    current_turn: DiscordAttributedTurn,
    *,
    reply_target: DiscordReplyTargetContext | None = None,
) -> DiscordSpeakerModelContext:
    history: list[dict[str, str]] = []
    for turn in previous_turns:
        history.append(
            {
                "role": "user",
                "content": attributed_user_content(turn, current_speaker=False),
            }
        )
        if turn.response_text is not None:
            history.append({"role": "assistant", "content": turn.response_text})
    return DiscordSpeakerModelContext(
        history=history,
        reply_target_message=(
            {
                # Keep quoted target text at user role. The header is trusted
                # backend metadata, while the quoted Discord text remains
                # untrusted user content and must not be elevated to system.
                "role": "user",
                "content": reply_target_content(reply_target),
            }
            if reply_target is not None
            else None
        ),
        current_message={
            "role": "user",
            "content": attributed_user_content(current_turn, current_speaker=True),
        },
    )
