"""Create PostgreSQL document-worker foundation tables."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260717_01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("documents", sa.Column("id", sa.String(128), primary_key=True), sa.Column("original_filename", sa.Text(), nullable=False), sa.Column("stored_filename", sa.Text(), nullable=False), sa.Column("mime_type", sa.String(255)), sa.Column("file_size", sa.Integer()), sa.Column("content_hash", sa.String(64), nullable=False, unique=True), sa.Column("status", sa.String(32), nullable=False), sa.Column("active_version_id", sa.String(128)), sa.Column("source_available", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("indexed_at", sa.DateTime(timezone=True)), sa.Column("last_accessed_at", sa.DateTime(timezone=True)), sa.Column("error_message", sa.Text()))
    op.create_index("ix_documents_status", "documents", ["status"])
    op.create_index("ix_documents_content_hash", "documents", ["content_hash"])
    op.create_table("document_versions", sa.Column("id", sa.String(128), primary_key=True), sa.Column("document_id", sa.String(128), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False), sa.Column("version_number", sa.Integer(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("parser_name", sa.String(128)), sa.Column("parser_version", sa.String(128)), sa.Column("ocr_model", sa.String(255)), sa.Column("embedding_model", sa.String(255)), sa.Column("chunking_config", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("activated_at", sa.DateTime(timezone=True)), sa.Column("superseded_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("document_id", "version_number", name="uq_document_version_number"))
    op.create_table("ingestion_runs", sa.Column("id", sa.String(128), primary_key=True), sa.Column("document_id", sa.String(128), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False), sa.Column("version_id", sa.String(128), sa.ForeignKey("document_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("current_stage", sa.String(32), nullable=False), sa.Column("total_pages", sa.Integer(), nullable=False, server_default="0"), sa.Column("processed_pages", sa.Integer(), nullable=False, server_default="0"), sa.Column("ocr_pages", sa.Integer(), nullable=False, server_default="0"), sa.Column("total_chunks", sa.Integer(), nullable=False, server_default="0"), sa.Column("embedded_chunks", sa.Integer(), nullable=False, server_default="0"), sa.Column("progress_percent", sa.Integer(), nullable=False, server_default="0"), sa.Column("attempt", sa.Integer(), nullable=False, server_default="1"), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("error_code", sa.String(64)), sa.Column("error_message", sa.Text()))
    op.create_table("document_pages", sa.Column("id", sa.String(128), primary_key=True), sa.Column("document_id", sa.String(128), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False), sa.Column("version_id", sa.String(128), sa.ForeignKey("document_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("page_number", sa.Integer(), nullable=False), sa.Column("native_text", sa.Text()), sa.Column("ocr_text", sa.Text()), sa.Column("selected_text", sa.Text()), sa.Column("extraction_method", sa.String(16), nullable=False), sa.Column("native_quality_score", sa.Float()), sa.Column("ocr_quality_score", sa.Float()), sa.Column("render_dpi", sa.Integer()), sa.Column("status", sa.String(32), nullable=False), sa.Column("error_message", sa.Text()), sa.UniqueConstraint("version_id", "page_number", name="uq_document_page_version_number"))
    op.create_table("document_chunks", sa.Column("id", sa.String(128), primary_key=True), sa.Column("chunk_uid", sa.String(128), nullable=False), sa.Column("document_id", sa.String(128), sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False), sa.Column("version_id", sa.String(128), sa.ForeignKey("document_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("chunk_index", sa.Integer(), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("content_hash", sa.String(64), nullable=False), sa.Column("page_start", sa.Integer()), sa.Column("page_end", sa.Integer()), sa.Column("section_title", sa.Text()), sa.Column("block_type", sa.String(32), nullable=False), sa.Column("token_count", sa.Integer()), sa.Column("extraction_method", sa.String(16), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("document_id", "version_id", "chunk_index", name="uq_document_chunk_version_index"), sa.UniqueConstraint("chunk_uid", name="uq_document_chunk_uid"))
    op.create_table("jobs", sa.Column("id", sa.String(128), primary_key=True), sa.Column("job_type", sa.String(64), nullable=False), sa.Column("document_id", sa.String(128), sa.ForeignKey("documents.id", ondelete="CASCADE")), sa.Column("version_id", sa.String(128), sa.ForeignKey("document_versions.id", ondelete="CASCADE")), sa.Column("ingestion_run_id", sa.String(128), sa.ForeignKey("ingestion_runs.id", ondelete="CASCADE")), sa.Column("status", sa.String(32), nullable=False), sa.Column("priority", sa.Integer(), nullable=False, server_default="0"), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"), sa.Column("max_attempts", sa.Integer(), nullable=False, server_default="3"), sa.Column("available_at", sa.DateTime(timezone=True)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("worker_id", sa.String(128)), sa.Column("error_message", sa.Text()), sa.Column("payload", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.create_table("outbox_events", sa.Column("id", sa.String(128), primary_key=True), sa.Column("event_type", sa.String(64), nullable=False), sa.Column("aggregate_type", sa.String(64), nullable=False), sa.Column("aggregate_id", sa.String(128), nullable=False), sa.Column("payload", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("status", sa.String(32), nullable=False), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"), sa.Column("available_at", sa.DateTime(timezone=True)), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("processed_at", sa.DateTime(timezone=True)), sa.Column("last_error", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))


def downgrade() -> None:
    for table in ("outbox_events", "jobs", "document_chunks", "document_pages", "ingestion_runs", "document_versions", "documents"):
        op.drop_table(table)
