"""Refuse to train on anything that overlaps a set we measure on.

Two independent leaks, because they fail in different ways and only one of them
is visible to an n-gram check:

1. TEXT overlap. A training row that contains a passage from the eval corpus
   turns the gate into a memory test. Caught here by shared word n-grams.

2. CONSTRUCTION overlap. A "held-out" set generated by the same model under the
   same prompt template as the training set shares that generator's habits,
   vocabulary and blind spots. Every row differs, no n-gram matches, and the
   held-out score is still optimistic — which is the more dangerous of the two,
   because it looks clean. Caught here by comparing the manifest's `generator`
   and `template` fields, not the text.

Usage:
    python -m training.common.leak_check --candidate training/reranker/queries.jsonl
    python -m training.common.leak_check --construction-only
"""
from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = PROJECT_ROOT / "data" / "evaluation" / "split_manifest.json"

DEFAULT_N = 8
# Below this the match is idiom, not contamination: Vietnamese technical prose
# repeats long stock phrases ("theo cấu hình đang chạy", API names, headings).
# Above it, something was copied. Tuned to flag, not to adjudicate — the script
# prints the matching n-grams so a person makes the call.
DEFAULT_THRESHOLD = 0.02

_WORD = re.compile(r"\w+", re.UNICODE)


def words(text: str) -> list[str]:
    return _WORD.findall(text.lower())


def ngrams(text: str, n: int) -> set[tuple[str, ...]]:
    tokens = words(text)
    return {tuple(tokens[i : i + n]) for i in range(len(tokens) - n + 1)}


def text_of(path: Path) -> str:
    """Every string in a file, whatever shape the file has."""
    if path.is_dir():
        return "\n".join(text_of(item) for item in sorted(path.rglob("*")) if item.is_file())
    raw = path.read_text(encoding="utf-8", errors="replace")
    if path.suffix == ".jsonl":
        pieces = []
        for line in raw.splitlines():
            if line.strip():
                try:
                    pieces.append(" ".join(_strings(json.loads(line))))
                except json.JSONDecodeError:
                    pieces.append(line)
        return "\n".join(pieces)
    if path.suffix == ".json":
        try:
            return " ".join(_strings(json.loads(raw)))
        except json.JSONDecodeError:
            return raw
    return raw


def _strings(value) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        return [s for item in value.values() for s in _strings(item)]
    if isinstance(value, list):
        return [s for item in value for s in _strings(item)]
    return []


def load_manifest() -> list[dict]:
    if not MANIFEST.exists():
        raise SystemExit(f"No manifest at {MANIFEST}. Run: python -m training.common.split_manifest --write")
    return json.loads(MANIFEST.read_text(encoding="utf-8"))["artifacts"]


def check_construction(artifacts: list[dict]) -> list[str]:
    """A held-out set built like the training set is not held out."""
    problems = []
    trains = [a for a in artifacts if a["role"] == "train"]
    protected = [a for a in artifacts if a["role"] in {"gate", "heldout"}]
    for train in trains:
        for other in protected:
            if train.get("generator") in (None, "human") and other.get("generator") in (None, "human"):
                continue
            if train.get("generator") == other.get("generator") and train.get("template") == other.get("template"):
                problems.append(
                    f"{other['path']} ({other['role']}) shares generator={other.get('generator')!r} "
                    f"and template={other.get('template')!r} with training set {train['path']} — "
                    f"it measures the generator, not the model"
                )
    return problems


def check_text(candidate: Path, artifacts: list[dict], n: int, threshold: float) -> list[str]:
    candidate_ngrams = ngrams(text_of(candidate), n)
    if not candidate_ngrams:
        raise SystemExit(f"{candidate} yielded no {n}-grams — wrong file, or shorter than {n} words per row?")
    problems = []
    print(f"candidate: {candidate}  ({len(candidate_ngrams):,} distinct {n}-grams)")
    for artifact in artifacts:
        if artifact["role"] not in {"gate", "heldout"}:
            continue
        path = PROJECT_ROOT / artifact["path"]
        if not path.exists():
            problems.append(f"{artifact['path']}: listed in the manifest, missing on disk")
            continue
        protected = ngrams(text_of(path), n)
        if not protected:
            continue
        shared = candidate_ngrams & protected
        ratio = len(shared) / len(protected)
        marker = "LEAK" if ratio > threshold else "ok  "
        print(f"  {marker} {ratio:7.4f}  {len(shared):6,} / {len(protected):7,}  {artifact['path']}")
        if ratio > threshold:
            sample = ["…".join([" ".join(g)]) for g in list(shared)[:3]]
            problems.append(
                f"{artifact['path']} ({artifact['role']}): {ratio:.2%} of its {n}-grams appear in the candidate. "
                f"Examples: {sample}"
            )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--candidate", help="Training file to check against every gate/heldout set.")
    parser.add_argument("--construction-only", action="store_true", help="Skip text overlap; only check generator/template collisions.")
    parser.add_argument("--n", type=int, default=DEFAULT_N)
    parser.add_argument("--threshold", type=float, default=DEFAULT_THRESHOLD)
    arguments = parser.parse_args()

    artifacts = load_manifest()
    problems = check_construction(artifacts)
    if not arguments.construction_only:
        if not arguments.candidate:
            parser.error("--candidate is required unless --construction-only is given")
        problems += check_text(Path(arguments.candidate), artifacts, arguments.n, arguments.threshold)

    if problems:
        print("\nleak_check FAILED:")
        for problem in problems:
            print(f"  - {problem}")
        return 1
    print("\nleak_check OK.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
