"""Structural contract for the auxiliary store (conversations, memories, OCR
console, request log).

PostgresAuxiliaryStore is the only implementation — the SQLite adapter this
Protocol once abstracted over was removed in the PostgreSQL cutover. The
Protocol is kept because services type against it, but it must mirror the real
adapter exactly; letting it drift hides signature errors from every checker.
"""
from __future__ import annotations

from typing import Protocol


class AuxiliaryStore(Protocol):
    def healthcheck(self) -> bool: ...
    def conversation_exists(self, conversation_id: str) -> bool: ...
    def create_conversation(self, conversation_id: str, title: str | None = None, user_id: str | None = None) -> None: ...
    def conversation_owner(self, conversation_id: str) -> str | None: ...
    def set_conversation_title(self, conversation_id: str, title: str) -> bool: ...
    # Returns the new message id; `sources` are the citations of a RAG answer
    # and are written in the same transaction as the message itself.
    def add_message(self, conversation_id: str, role: str, content: str, model_used: str | None = None, sources: list[dict[str, object]] | None = None) -> int: ...
    def get_messages(self, conversation_id: str, limit: int) -> list[dict[str, str]]: ...
    def add_agent_traces(self, conversation_id: str, message_id: int | None, steps: list[dict[str, object]]) -> None: ...
    def get_agent_traces(self, message_id: int) -> list[dict[str, object]]: ...
    def list_conversations(self, owner_user_id: str | None = None) -> list[dict[str, object]]: ...
    def get_conversation(self, conversation_id: str) -> dict[str, object] | None: ...
    def delete_conversation(self, conversation_id: str) -> bool: ...
    def create_memory(self, memory_id: str, content: str, memory_type: str, importance: float) -> None: ...
    def get_memory(self, memory_id: str) -> dict[str, object] | None: ...
    def update_memory(self, memory_id: str, content: str, memory_type: str, importance: float) -> bool: ...
    def delete_memory(self, memory_id: str) -> bool: ...
    def log_request(self, endpoint: str, model_used: str | None, latency_ms: int, status: str, error_code: str | None = None) -> None: ...
    def save_ocr_run(self, run_id: str, filename: str, status: str, model: str, result_json: str) -> None: ...
    def list_ocr_runs(self) -> list[dict[str, object]]: ...
    def delete_ocr_run(self, run_id: str) -> bool: ...
