const $=id=>document.getElementById(id);let selectedFile=null,documentId=null,conversationId=null;
const api=async(path,options={})=>{const response=await fetch(path,options);const data=response.status===204?{}:await response.json();if(!response.ok)throw new Error(data.message||'Yêu cầu thất bại');return data;};
function addMessage(role,text){const item=document.createElement('article');item.className=`message ${role}`;item.innerHTML=`<span>${role==='user'?'Bạn':'AI'}</span><p></p>`;item.querySelector('p').textContent=text;$('messages').append(item);$('messages').scrollTop=$('messages').scrollHeight;return item.querySelector('p');}
function preview(file){const box=$('preview');const url=URL.createObjectURL(file);if(file.type==='application/pdf'){box.innerHTML='';const frame=document.createElement('iframe');frame.src=url;box.append(frame);}else if(file.type.startsWith('text/')||file.name.endsWith('.md')){const reader=new FileReader();reader.onload=()=>{box.innerHTML='<pre></pre>';box.querySelector('pre').textContent=reader.result;};reader.readAsText(file);}else{box.innerHTML='<div class="preview-empty">Không thể preview trực tiếp định dạng này. Tài liệu vẫn có thể được tải và lập chỉ mục.</div>';}}
function chooseFile(file){if(!file)return;selectedFile=file;$('upload').disabled=false;$('file-status').textContent=`Đã chọn: ${file.name} · ${(file.size/1024/1024).toFixed(2)} MB`;preview(file);}
const zone=$('dropzone');zone.onclick=()=>$('file-input').click();$('file-input').onchange=e=>chooseFile(e.target.files[0]);['dragenter','dragover'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.add('drag');}));['dragleave','drop'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.remove('drag');}));zone.addEventListener('drop',e=>chooseFile(e.dataTransfer.files[0]));
$('upload').onclick=async()=>{if(!selectedFile)return;const form=new FormData();form.append('file',selectedFile);$('upload').disabled=true;$('file-status').textContent='Đang tải lên…';try{const upload=await api('/documents/upload',{method:'POST',body:form});$('file-status').textContent='Đang lập chỉ mục…';const index=await api('/documents/index',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_id:upload.document_id})});documentId=upload.document_id;$('file-status').textContent=`Sẵn sàng · ${index.chunks_created} đoạn`;const list=$('document-list');list.innerHTML=`<div class="document active" title="${documentId}">${upload.filename}<br><small>${index.chunks_created} chunks</small></div>`;$('use-source').checked=true;updateMode();}catch(error){$('file-status').textContent=`Lỗi: ${error.message}`;$('upload').disabled=false;}};
function updateMode(){$('chat-mode').textContent=$('use-source').checked?'RAG · dùng tài liệu nguồn':'LLM gốc · không dùng tài liệu';}$('use-source').onchange=updateMode;
async function stream(path,payload,target){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,stream:true})});if(!response.ok)throw new Error((await response.json()).message||'Model không phản hồi');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',answer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop();for(const event of events){const type=event.match(/^event: (.+)$/m)?.[1],raw=event.match(/^data: (.+)$/m)?.[1];if(!raw)continue;const data=JSON.parse(raw);if(type==='meta'&&data.conversation_id)conversationId=data.conversation_id;if(type==='token'){answer+=data.content;target.textContent=answer;$('messages').scrollTop=$('messages').scrollHeight;}if(type==='error')throw new Error(data.message||'Lỗi khi sinh phản hồi');}}}
$('chat-form').onsubmit=async e=>{e.preventDefault();const prompt=$('prompt').value.trim();if(!prompt)return;if($('use-source').checked&&!documentId){addMessage('assistant','Hãy tải lên và lập chỉ mục tài liệu trước khi bật chế độ dùng tài liệu.');return;}$('prompt').value='';addMessage('user',prompt);const target=addMessage('assistant','');try{if($('use-source').checked)await stream('/rag/chat',{message:prompt,document_id:documentId},target);else await stream('/chat',{message:prompt,conversation_id:conversationId,use_memory:$('use-memory').checked},target);}catch(error){target.textContent=`Lỗi: ${error.message}`;}};
$('new-chat').onclick=()=>{conversationId=null;$('messages').innerHTML='';addMessage('assistant','Cuộc trò chuyện mới đã sẵn sàng.');};$('close-preview').onclick=()=>{$('preview').className='preview-empty';$('preview').textContent='Chọn một tệp để xem nội dung tại đây.';};api('/health').then(x=>$('health').textContent=`API ${x.status} · Ollama ${x.ollama}`).catch(()=>$('health').textContent='API chưa sẵn sàng');
