const $=id=>document.getElementById(id);let selectedFile=null,conversationId=null;const selectedDocuments=new Set();
const api=async(path,options={})=>{const response=await fetch(path,options);const data=response.status===204?{}:await response.json();if(!response.ok)throw new Error(data.message||'Yêu cầu thất bại');return data;};
function addMessage(role,text){const item=document.createElement('article');item.className=`message ${role}`;item.innerHTML=`<span>${role==='user'?'Bạn':'AI'}</span><p></p>`;item.querySelector('p').textContent=text;$('messages').append(item);$('messages').scrollTop=$('messages').scrollHeight;return item.querySelector('p');}
function preview(file){const box=$('preview'),url=URL.createObjectURL(file);if(file.type==='application/pdf'){box.innerHTML='';const frame=document.createElement('iframe');frame.src=url;box.append(frame);}else if(file.type.startsWith('text/')||file.name.endsWith('.md')){const reader=new FileReader();reader.onload=()=>{box.innerHTML='<pre></pre>';box.querySelector('pre').textContent=reader.result;};reader.readAsText(file);}else box.innerHTML='<div class="preview-empty">Không thể preview trực tiếp định dạng này.</div>';}
function chooseFile(file){if(!file)return;selectedFile=file;$('upload').disabled=false;$('file-status').textContent=`Đã chọn: ${file.name} · ${(file.size/1024/1024).toFixed(2)} MB`;preview(file);}
async function refreshDocuments(){const documents=await api('/documents');const list=$('document-list');if(!documents.length){list.innerHTML='<p>Chưa có tài liệu nguồn.</p>';return;}for(const id of [...selectedDocuments]){const document=documents.find(doc=>doc.document_id===id);if(!document||document.status!=='indexed')selectedDocuments.delete(id);}list.innerHTML='';for(const doc of documents){const row=document.createElement('label');row.className='document';row.innerHTML=`<input type="checkbox" ${selectedDocuments.has(doc.document_id)?'checked':''} ${doc.status==='indexed'?'':'disabled'}><div><div class="document-name"></div><div class="document-meta"></div></div>`;row.querySelector('.document-name').textContent=doc.filename;row.querySelector('.document-meta').textContent=doc.status==='indexed'?`${doc.chunks_count} đoạn · ${doc.source_available?'có nguồn':'không còn file gốc'}`:doc.status;row.querySelector('input').onchange=e=>{e.target.checked?selectedDocuments.add(doc.document_id):selectedDocuments.delete(doc.document_id);syncSelectAll(documents);updateMode();};list.append(row);}syncSelectAll(documents);updateMode();}
function syncSelectAll(documents=[]){const enabled=documents.filter(doc=>doc.status==='indexed');const all=$('select-all');all.checked=enabled.length>0&&enabled.every(doc=>selectedDocuments.has(doc.document_id));all.indeterminate=enabled.some(doc=>selectedDocuments.has(doc.document_id))&&!all.checked;}
async function waitForIngestion(runId){while(true){const run=await api(`/documents/ingestions/${runId}`);$('file-status').textContent=`${run.stage} · ${run.vectors_count}/${run.chunks_count||'?'} vectors`;if(['indexed','failed','partial','cancelled'].includes(run.status))return run;await new Promise(resolve=>setTimeout(resolve,700));}}
const zone=$('dropzone');zone.onclick=()=>$('file-input').click();$('file-input').onchange=e=>chooseFile(e.target.files[0]);['dragenter','dragover'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.add('drag');}));['dragleave','drop'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.remove('drag');}));zone.addEventListener('drop',e=>chooseFile(e.dataTransfer.files[0]));
$('select-all').onchange=async e=>{const docs=await api('/documents');for(const doc of docs)if(doc.status==='indexed'){if(e.target.checked)selectedDocuments.add(doc.document_id);else selectedDocuments.delete(doc.document_id);}await refreshDocuments();};
$('upload').onclick=async()=>{if(!selectedFile)return;$('upload').disabled=true;$('file-status').textContent='Đang tải lên…';try{const form=new FormData();form.append('file',selectedFile);const upload=await api('/documents/upload',{method:'POST',body:form});if(!(upload.duplicate&&upload.status==='indexed')){const index=await api('/documents/index',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_id:upload.document_id})});const run=await waitForIngestion(index.ingestion_run_id);if(run.status!=='indexed')throw new Error(run.error_message||`Index ${run.status}`);$('file-status').textContent=`Sẵn sàng · ${run.chunks_count} đoạn`;}else $('file-status').textContent='Tài liệu trùng đã được dùng lại.';selectedDocuments.add(upload.document_id);$('use-source').checked=true;await refreshDocuments();}catch(error){$('file-status').textContent=`Lỗi: ${error.message}`;$('upload').disabled=false;}};
function updateMode(){$('chat-mode').textContent=$('use-source').checked?`RAG · ${selectedDocuments.size} tài liệu đã chọn`:'LLM gốc · không dùng tài liệu';}$('use-source').onchange=updateMode;
async function stream(path,payload,target){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,stream:true})});if(!response.ok)throw new Error((await response.json()).message||'Model không phản hồi');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',answer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop();for(const event of events){const type=event.match(/^event: (.+)$/m)?.[1],raw=event.match(/^data: (.+)$/m)?.[1];if(!raw)continue;const data=JSON.parse(raw);if(type==='meta'&&data.conversation_id)conversationId=data.conversation_id;if(type==='token'){answer+=data.content;target.textContent=answer;$('messages').scrollTop=$('messages').scrollHeight;}if(type==='error')throw new Error(data.message||'Lỗi khi sinh phản hồi');}}}
$('chat-form').onsubmit=async e=>{e.preventDefault();const prompt=$('prompt').value.trim();if(!prompt)return;if($('use-source').checked&&!selectedDocuments.size){addMessage('assistant','Hãy chọn ít nhất một tài liệu đã index ở cột bên trái.');return;}$('prompt').value='';addMessage('user',prompt);const target=addMessage('assistant','');try{if($('use-source').checked)await stream('/rag/chat',{message:prompt,document_ids:[...selectedDocuments]},target);else await stream('/chat',{message:prompt,conversation_id:conversationId,use_memory:$('use-memory').checked},target);}catch(error){target.textContent=`Lỗi: ${error.message}`;}};
$('prompt').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();$('chat-form').requestSubmit();}});
function installResizer(id,side){const handle=$(id),workspace=$('workspace');handle.addEventListener('pointerdown',event=>{handle.setPointerCapture(event.pointerId);handle.classList.add('dragging');const move=e=>{const width=side==='left'?e.clientX:window.innerWidth-e.clientX;workspace.style.setProperty(side==='left'?'--left':'--right',`${Math.max(200,Math.min(520,width))}px`);};const up=()=>{handle.classList.remove('dragging');handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',up);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',up);});}installResizer('left-resizer','left');installResizer('right-resizer','right');
$('new-chat').onclick=()=>{conversationId=null;$('messages').innerHTML='';addMessage('assistant','Cuộc trò chuyện mới đã sẵn sàng.');};$('close-preview').onclick=()=>{$('preview').className='preview-empty';$('preview').textContent='Chọn một tệp để xem nội dung tại đây.';};api('/health').then(x=>$('health').textContent=`API ${x.status} · Ollama ${x.ollama}`).catch(()=>$('health').textContent='API chưa sẵn sàng');refreshDocuments().catch(()=>{});
